[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1a1b26"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor]
style = "Block"
unfocused_hollow = false

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.95
blur = true
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
{key = "F", mods = "Control", chars = "tmux\n tmux-sessionizer\n" }
]


